Stream Manager APIs, Screens, & Related Components
livepeer/pipelines pull request #32
Opened 2024-12-13 17:14 UTC by 0xspeedybird

Add stream manager support:

- Update APIs to edit, delete, create streams
- Connect pipeline search to backend in order to make it functional
- Externalize URLs to .env config
- Add Manage and Create Streams to navbar
- Create components for Stream Form
- Remove usage of supabase from client and protect credentials
- Add screens to view logged in users streams and create/edit streams

2024-12-13 19:17 UTC, thomshutt approved these changes

2024-12-13 20:54 UTC, suhailkakar requested changes

2024-12-13 20:54 UTC, suhailkakar commented on apps/app/.env.example
> +NEXT_PUBLIC_STREAM_STATUS_ENDPOINT_URL="https://mygateway.nope/stream-status"
@0xspeedybird i'm not really sure what is this link (mygateway.nope) - can you please elaborate?

2024-12-13 20:54 UTC, suhailkakar commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
`streamId` should always be generated by the server app to prevent invalid text and ensure all IDs follow the same format (str....)

2024-12-13 20:54 UTC, suhailkakar commented on apps/app/app/stream/[id]/page.tsx
if possible, let's make sure the main page (stream/id) is a server component (without explicitly mentioning use client). for nested components, we can add client components as needed, but the main page itself should remain a server component. 

i'm also working on applying this approach to other pages.

2024-12-13 20:54 UTC, suhailkakar commented on apps/app/app/streams/my-streams/page.tsx
same comment:

if possible, let's make sure the main page (stream/id) is a server component (without explicitly mentioning use client). for nested components, we can add client components as needed, but the main page itself should remain a server component.

i'm also working on applying this approach to other pages.

2024-12-13 21:13 UTC, 0xspeedybird commented on apps/app/.env.example
> +NEXT_PUBLIC_STREAM_STATUS_ENDPOINT_URL="https://mygateway.nope/stream-status"
It's a mock URL.  For prod, this needs to point to the Gateway API for stream status.

2024-12-13 21:14 UTC, 0xspeedybird commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
It will.  This code is to support both create and edit scenarios.  In an edit scenario, the existing id would be used.  In a create scenario, it will be null and then use the newId function to create an id as you mention is required.

2024-12-13 21:19 UTC, 0xspeedybird commented on apps/app/app/stream/[id]/page.tsx
Will do

2024-12-13 21:19 UTC, 0xspeedybird commented on apps/app/app/streams/my-streams/page.tsx
Will do

2024-12-13 21:57 UTC, suhailkakar commented on apps/app/.env.example
> +NEXT_PUBLIC_STREAM_STATUS_ENDPOINT_URL="https://mygateway.nope/stream-status"
can we please replace this with the correct Gateway API for now?

2024-12-13 21:58 UTC, suhailkakar commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
> This code is to support both create and edit scenarios

Then, it would be much better to create a separate action for update stream. From the file name `create.ts`, this should handle only the creation of the stream

2024-12-13 22:00 UTC, suhailkakar commented on apps/app/app/stream/[id]/page.tsx
- you can replace useEffect with calling the function directly[1] and passing it to child 
- you can remove the useState and add them to specific children client component 

[1] https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

2024-12-13 22:28 UTC, 0xspeedybird commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
Well the action code is doing an upsert.  How about we change the action name to upsert.ts?  This way the logic is centralized rather than in separate files.

2024-12-13 22:32 UTC, 0xspeedybird commented on apps/app/.env.example
> +NEXT_PUBLIC_STREAM_STATUS_ENDPOINT_URL="https://mygateway.nope/stream-status"
I updated it to the URL I got from @victorges

2024-12-14 05:15 UTC, 0xspeedybird commented on apps/app/app/stream/[id]/page.tsx
I'll look into this after we get everything else validated with the E2E flow, unless this is causing a defect right now.

2024-12-14 23:53 UTC, victorges commented on apps/app/hooks/useStreamStatus.ts
> +                // example output from api -> {"input_fps":23.992516753574126,"last_error":null,"last_error_time":null,"last_input_time":1734119451.551498,"last_output_time":1734119451.5212831,"last_
Hey, we've actually changed this schema a bit to follow the requested schema from the product team. It didn't change a lot, we just nested some of the fields into separate `input_status` and `inference_status` sub-objects, plus added a higher-level `state` which you can also use as well to show some user-friendly state on the UI.

Sorry, I didn't know you were already implementing the integration before we got the API working, so maybe I didn't warn you. But I think this typescript definition of the response object can get you started more easily:
```ts
type PipelineStatus = {
  type: "status";
  pipeline: string;
  start_time: number;
  state: "OFFLINE" | "ONLINE" | "DEGRADED_INPUT" | "DEGRADED_INFERENCE";
  last_state_update_time: number | null;
  input_status: {
    last_input_time: number | null;
    fps: number;
  };
  inference_status: {
    last_output_time: number | null;
    fps: number;
    last_params_update_time: number | null;
    last_params: Record<string, any> | null;
    last_params_hash: string | null;
    last_error_time: number | null;
    last_error: string | null;
    last_restart_time: number | null;
    last_restart_logs: string[] | null;
    restart_count: number;
  };
};
```

Also, now all timestmaps are in unix millis, similar to node 🙏

2024-12-15 15:33 UTC, 0xspeedybird commented on apps/app/hooks/useStreamStatus.ts
> +                // example output from api -> {"input_fps":23.992516753574126,"last_error":null,"last_error_time":null,"last_input_time":1734119451.551498,"last_output_time":1734119451.5212831,"last_
Do you know if the stream state field above is provided in the response or if I need to calculate it based on the nested status fields?  I would assume the former but want to be 100% clear before making further changes to the code.

fyi, I went off of a requirements doc from Xilin and have asked her to align those requirements with your statements above.

2024-12-15 15:43 UTC, victorges commented on apps/app/hooks/useStreamStatus.ts
> +                // example output from api -> {"input_fps":23.992516753574126,"last_error":null,"last_error_time":null,"last_input_time":1734119451.551498,"last_output_time":1734119451.5212831,"last_
The state comes in the response! And we might be based on the same doc, I also synced with Xilin to build that 😄

2024-12-16 15:11 UTC, suhailkakar commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
Sure, sounds good

2024-12-16 16:24 UTC, suhailkakar approved these changes

2024-12-16 22:26 UTC, 0xspeedybird commented on apps/app/app/api/streams/create.ts
> +  const streamId = streamData?.id || newId("stream");
Done

2024-12-16 22:33 UTC, merged